version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy Environment
          command: |
            aws cloudfromation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
          when: on_fail
jobs:
  smoke_test:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: simulate error
          command: |
            return 1
      - destroy_environment


  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "create infra"
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name prod-${CIRCLE_WORKFLOW_ID}

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
      - smoke_test:
          requires:
            - create_infrastructure
