version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy Environment
          command: |
            aws cloudfromation delete-stack --stack-name prod-${CIRCLECI_WORKFLOW_ID}

jobs:
  smoke_test:
      docker:
        - image: amazon/aws-cli
      steps:
        - run: apk add --update curl
        - run:
            name: simulate error
            command: |
              return 1
        - destroy_environment
            when: on_fail

  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "create infra"
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name prod-${CIRCLECI_WORKFLOW_ID}

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
      - smoke_test:
          requires:
            - configure_infrastructure
